// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivthhmsbgmdslmvgphin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2dGhobXNiZ21kc2xtdmdwaGluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzU1NjMsImV4cCI6MjA2NTU1MTU2M30.9UWEptbPaftzdNn_rmVvl3gfFbFyO1FgaUZwmJFM23s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);